name: Code review
on: [push, pull_request]
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: 'true'
        fetch-depth: 0
    - run: |
        git fetch --no-tags --prune origin
    - uses: adwerx/pronto-ruby@v2.9
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        RUBOCOP_CONFIG: ./pronto/rubocop/rubocop.yml
      with:
        runners: >-
          brakeman rails_best_practices reek rubocop
